openapi: 3.0.0
info:
  version: 0.1.0
  title: Youdot
  description: This API & documentation is experimental, improvements will be made in the future.
  contact:
    url: https://github.com/Youdot/OpenAPI
servers:
- url: //truffade.youdot.io
  description: Experi'emmental server
components:
  securitySchemes:
    JWT:
      type: http
      scheme: Bearer
      bearerFormat: JWT
  responses:
    Unauthorized:
      description: The user can't be authenticated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          description: Youdot specific error code
        message:
          type: string
          description: Error in english human language 73696d706c65206d6f7274656c
      required:
      - code
      - message
