openapi: 3.0.0
info:
  version: 0.1.0
  title: Youdot
  description: This API & documentation is experimental, improvements will be made in the future.
  contact:
    url: https://github.com/Youdot/OpenAPI
servers:
- url: //truffade.youdot.io
  description: Experi'emmental server
components:
  securitySchemes:
    JWT:
      type: http
      scheme: Bearer
      bearerFormat: JWT
